import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { ViewTransitions } from "next-view-transitions";
import SmoothScroller from "./utilis/SmoothScrolling";
import localFont from "next/font/local";
import Preloader from "@/components/Preloader";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const amiamie = localFont({
  src: [
    { path: "../fonts/Amiamie-Black.woff2", weight: "900", style: "normal" },
    { path: "../fonts/Amiamie-Regular.woff2", weight: "400", style: "normal" },
  ],
  variable: "--font-amiamie",
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${amiamie.variable} antialiased p-4`}>
          <Preloader />
          <Header />
          {children}
          <SmoothScroller />
        </body>
      </html>
    </ViewTransitions>
  );
}
